feature:
    - head-branch: ["^feat"]

fix:
    - head-branch: ["^fix"]

docs:
    - head-branch: ["^docs"]

style:
    - head-branch: ["^style"]

refactor:
    - head-branch: ["^refactor"]

perf:
    - head-branch: ["^perf"]

test:
    - head-branch: ["^test"]

build:
    - head-branch: ["^build"]

ci:
    - head-branch: ["^ci"]

chore:
    - head-branch: ["^chore"]

revert:
    - head-branch: ["^revert"]
