changelog:
    exclude:
        labels:
            - ignore-for-release
    categories:
        - title: Breaking Changes 💥
          labels:
              - breaking
        - title: New Features ✨
          labels:
              - feature
        - title: Improvements 🚀
          labels:
              - docs
              - style
              - refactor
              - perf
              - test
        - title: Fixes 🐛
          labels:
              - fix
        - title: Maintenance 🔧
          label:
              - build
              - ci
              - chore
              - revert
