name: "Lint PR"

on:
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize

permissions:
    pull-requests: read

jobs:
    main:
        name: Lint PR title
        runs-on: ubuntu-latest
        steps:
            - name: semantic-pull-request
              uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
