name: main

on:
    push:
        branches:
            - main
        tags:
            - "**"
    pull_request:
        branches:
            - main

jobs:
    cicd:
        name: CICD
        runs-on: ubuntu-latest
        env:
            ENVIRONMENT: prod
            IMAGE_TAG: ${{ github.ref_name }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12

            - name: Poetry cache
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/pip
                      ~/.cache/pypoetry
                  key: ${{ runner.os }}-pypoetry-${{ hashFiles('**/poetry.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-pypoetry-${{ hashFiles('**/poetry.lock') }}
                      ${{ runner.os }}-pypoetry-

            - name: Run CI
              run: ENVIRONMENT=ci make run-ci

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker CI
              run: ENVIRONMENT=ci make dc-ci

            - name: Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}
                      ghcr.io/${{ github.repository }}

            - name: Login to Docker Hub
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to GHCR
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  annotations: ${{ steps.meta.outputs.annotations }}
                  push: ${{ github.event_name != 'pull_request' }}
                  cache-from: type=gha
                  cache-to: ${{ (github.event_name != 'pull_request') && 'type=gha,mode=max' }}
