name: pr

on:
    pull_request:
        types:
            - opened
            - edited
            - reopened
            - synchronize

jobs:
    title-linter:
        name: lint title
        permissions:
            pull-requests: read
        runs-on: ubuntu-latest
        steps:
            - name: semantic-pull-request
              uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    labeler:
        name: label
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: labeler
              uses: actions/labeler@v5

    size-labeler:
        name: label size
        runs-on: ubuntu-latest
        steps:
            - uses: codelytv/pr-size-labeler@v1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
