name: push-to-master

on:
  push:
    branches:
      - master

jobs:
  cicd:
    name: CICD
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}

      - name: Run CI
        run: make run-ci

      - name: Docker login
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USER} --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USER: yxtay

      - name: Docker build
        run: make dc-build

      - name: Docker push
        run: make dc-push
