name: push-to-master

on:
  push:
    branches:
      - master

jobs:
  cicd:
    name: CICD
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}

      - name: Create env file
        run: |
          touch .env
          echo ENVIRONMENT=ci >> .env
          cat .env

      - name: Run CI
        run: make run-ci

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build
        run: make dc-build

      - name: Docker push
        run: make dc-push
